name: Bot Minerador do Brawl Stars

on:
  schedule:
    # Roda a cada 15 minutos
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  minerar_e_atualizar:
    runs-on: ubuntu-latest
    env:
      TZ: 'America/Sao_Paulo'
    permissions:
      contents: write

    steps:
      - name: Baixando os arquivos do repositório
        uses: actions/checkout@v4

      - name: Instalando o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalando as bibliotecas
        run: |
          pip install pandas brawlstats

      - name: Sincronizar e Configurar Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git pull --rebase origin main

      - name: Ver IP público do GitHub Actions
        run: |
          IP=$(curl -4 -fsS --max-time 10 https://api.ipify.org || true)
          if [ -z "$IP" ]; then
            IP=$(curl -4 -fsS --max-time 10 https://ifconfig.me || true)
          fi

          echo "=========================================="
          echo "IP PÚBLICO DO RUNNER DO GITHUB ACTIONS:"
          echo "${IP:-Não foi possível obter o IP}"
          echo "=========================================="

      - name: Rodando o Gerador (Bot)
        run: python gerador.py

      - name: Salvando as alterações no GitHub
        run: |
          git add historico_bruto.csv estatisticas_finais.csv rosters.json api/

          if ! git diff --cached --quiet; then
            git commit -m "🤖 Atualização Automática de Partidas e Rosters"
            git push origin main
          else
            echo "Sem mudanças para atualizar"
          fi
